<?xml version="1.0" encoding="utf-8"?><Database Name="LoginData" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Login" Member="Logins">
    <Type Name="Login">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="UserPassword" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="UserEmail" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>