<?xml version="1.0" encoding="utf-8"?><Database Name="KarateData" Class="AdminDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Members" Member="Members">
    <Type Name="Member">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FName" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="LName" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="Phone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Joined" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Instructors" Member="Instructors">
    <Type Name="Instructor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FName" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="LName" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
    </Type>
  </Table>
</Database>