#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logon
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LogonData")]
	public partial class NDSUDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAspNetUser(AspNetUser instance);
    partial void UpdateAspNetUser(AspNetUser instance);
    partial void DeleteAspNetUser(AspNetUser instance);
    #endregion
		
		public NDSUDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NDSUDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NDSUDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NDSUDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AspNetUser> AspNetUsers
		{
			get
			{
				return this.GetTable<AspNetUser>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AspNetUsers")]
	public partial class AspNetUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _AspUsername;
		
		private string _AspUserPassword;
		
		private string _AspUserType;
		
		private string _AspUserEmail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAspUsernameChanging(string value);
    partial void OnAspUsernameChanged();
    partial void OnAspUserPasswordChanging(string value);
    partial void OnAspUserPasswordChanged();
    partial void OnAspUserTypeChanging(string value);
    partial void OnAspUserTypeChanged();
    partial void OnAspUserEmailChanging(string value);
    partial void OnAspUserEmailChanged();
    #endregion
		
		public AspNetUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AspUsername", DbType="NChar(20)")]
		public string AspUsername
		{
			get
			{
				return this._AspUsername;
			}
			set
			{
				if ((this._AspUsername != value))
				{
					this.OnAspUsernameChanging(value);
					this.SendPropertyChanging();
					this._AspUsername = value;
					this.SendPropertyChanged("AspUsername");
					this.OnAspUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AspUserPassword", DbType="NChar(10)")]
		public string AspUserPassword
		{
			get
			{
				return this._AspUserPassword;
			}
			set
			{
				if ((this._AspUserPassword != value))
				{
					this.OnAspUserPasswordChanging(value);
					this.SendPropertyChanging();
					this._AspUserPassword = value;
					this.SendPropertyChanged("AspUserPassword");
					this.OnAspUserPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AspUserType", DbType="NChar(10)")]
		public string AspUserType
		{
			get
			{
				return this._AspUserType;
			}
			set
			{
				if ((this._AspUserType != value))
				{
					this.OnAspUserTypeChanging(value);
					this.SendPropertyChanging();
					this._AspUserType = value;
					this.SendPropertyChanged("AspUserType");
					this.OnAspUserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AspUserEmail", DbType="NChar(20)")]
		public string AspUserEmail
		{
			get
			{
				return this._AspUserEmail;
			}
			set
			{
				if ((this._AspUserEmail != value))
				{
					this.OnAspUserEmailChanging(value);
					this.SendPropertyChanging();
					this._AspUserEmail = value;
					this.SendPropertyChanged("AspUserEmail");
					this.OnAspUserEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
